version: "3.7"

services:
    cassandra:
        container_name: cassandra
        image: cassandra:latest
        restart: unless-stopped
        hostname: cassandra
        environment:
        - MAX_HEAP_SIZE=1G
        - HEAP_NEWSIZE=1G
        - CASSANDRA_CLUSTER_NAME=thp
        volumes:
        - ./cassandra/data:/var/lib/cassandra/data
        networks:
        - Hive

    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
        restart: unless-stopped
        ports:
            - '0.0.0.0:7200:9200'
        environment:
            - http.host=0.0.0.0
            - xpack.security.enabled=false
            - cluster.name=hive
            - bootstrap.memory_lock=true
            - script.allowed_types=inline
            - thread_pool.search.queue_size=100000
            - thread_pool.write.queue_size=10000
            - discovery.type=single-node
        ulimits:
          nofile:
              soft: 65536
              hard: 65536
          memlock:
              soft: -1
              hard: -1
        volumes:
            - ./elasticsearch/data:/usr/share/elasticsearch/data
            - ./elasticsearch/logs:/usr/share/elasticsearch/logs
        networks:
            - Hive
            
    cortex:
        image: thehiveproject/cortex:latest
        container_name: cortex
        restart: unless-stopped
        depends_on:
            - elasticsearch
        environment:
            - JOB_DIRECTORY=/opt/cortex/jobs
        ports:
            - "0.0.0.0:9001:9001"
        volumes:
            - ./cortex/application.conf:/etc/cortex/application.conf
            - /opt/cortex/jobs:/opt/cortex/jobs
            - /var/run/docker.sock:/var/run/docker.sock
            - ./cortex/log/:/var/log/cortex
            - /tmp:/tmp
        command: '--no-config --no-config-secret'
        networks:
            - Hive

    thehive:
        image: thehiveproject/thehive4:latest
        container_name: thehive
        restart: unless-stopped
        #embedded default admin@thehive.local:secret
        depends_on:
            - cortex
            - cassandra
        ports:
            - "0.0.0.0:7000:9000"
        volumes:
            - ./thehive/application.conf:/etc/thehive/application.conf
            - ./thehive/db:/opt/thp/thehive/db
            - ./thehive/index:/opt/thp/thehive/index
            - ./thehive/data:/opt/thp/thehive/data
        command: '--no-config --no-config-secret'
        networks:
            - Hive

networks:
    Hive:
        driver: bridge
