version: "3.7"

services:
  cassandra:
    container_name: cassandra
    image: cassandra:latest
    restart: unless-stopped
    hostname: cassandra
    environment:
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=1G
      - CASSANDRA_CLUSTER_NAME=thp
    volumes:
      - ./cassandra/data:/var/lib/cassandra/data
    networks:
      - Hive

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.1.2
    restart: unless-stopped
    hostname: elasticsearch
    ports:
      - '0.0.0.0:7200:9200'
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
    networks:
      - Hive
  
  thehive:
    container_name: thehive
    image: 'thehiveproject/thehive4:latest'
    restart: unless-stopped
    depends_on:
      - cassandra
    ports:
      - '0.0.0.0:7000:9000'
    volumes:
      - ./thehive/application.conf:/etc/thehive/application.conf
      - ./thehive/data:/opt/thp/thehive/data
      - ./thehive/index:/opt/thp/thehive/index
    networks:
      - Hive
      
networks:
    Hive:
        driver: bridge
